"""Evidence-grounded materials knowledge extraction."""

from .deepseek import (
    DeepSeekMaterialKnowledgeModel,
    MaterialKnowledgeReasoningError,
    MaterialKnowledgeReasoningModel,
)
from .extractor import (
    MaterialKnowledgeExtractor,
    build_material_knowledge_extractor,
)
from .models import (
    CompositionComponent,
    MaterialCondition,
    MaterialEntity,
    MaterialEntityProposal,
    MaterialExtractionLimits,
    MaterialExtractionModelTrace,
    MaterialKnowledgeDraft,
    MaterialKnowledgeExtractionRequest,
    MaterialKnowledgeExtractionResult,
    MaterialKnowledgeStatus,
    MaterialRelation,
    MaterialRelationProposal,
    MaterialRelationType,
    PropertyObservation,
    PropertyObservationProposal,
    ReportedValue,
    SimulationMethod,
    SimulationMethodProposal,
    StructureDescriptor,
    StructureKind,
    SynthesisProcedure,
    SynthesisProcedureProposal,
)

__all__ = [
    "CompositionComponent",
    "DeepSeekMaterialKnowledgeModel",
    "MaterialCondition",
    "MaterialEntity",
    "MaterialEntityProposal",
    "MaterialExtractionLimits",
    "MaterialExtractionModelTrace",
    "MaterialKnowledgeDraft",
    "MaterialKnowledgeExtractionRequest",
    "MaterialKnowledgeExtractionResult",
    "MaterialKnowledgeExtractor",
    "MaterialKnowledgeReasoningError",
    "MaterialKnowledgeReasoningModel",
    "MaterialKnowledgeStatus",
    "MaterialRelation",
    "MaterialRelationProposal",
    "MaterialRelationType",
    "PropertyObservation",
    "PropertyObservationProposal",
    "ReportedValue",
    "SimulationMethod",
    "SimulationMethodProposal",
    "StructureDescriptor",
    "StructureKind",
    "SynthesisProcedure",
    "SynthesisProcedureProposal",
    "build_material_knowledge_extractor",
]
